# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5aa4bbee65d28fc05cc213dfab0a140e979164deb88d5e48c0860853d82b8740e60215d787f0ac8730a7b3b3f6d5b5b66ed5c6ada1e6f1e17d1363f1c92be1f

test:
  secret_key_base: 4a65f4334d018fb650d8c6a6f64338e20e14292f42fc271b887a95e67f4ef01f6eb5d52097ca8b69951bd51ac13995406684e29306addafa5c521b9fd51111f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
